name: 1 - Generate Keystore (Run Once)
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore zad-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias zad-key-alias -dname "CN=Zad, OU=ZadApp, O=Zad, L=Alexandria, S=Alexandria, C=EG" -storepass zad123456 -keypass zad123456
          openssl base64 -A -in zad-release-key.jks -out keystore-base64.txt

      - name: Upload Keystore Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-keystore-files
          path: |
            zad-release-key.jks
            keystore-base64.txt
